/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import client.communication.Communication;
import communication.Operations;
import communication.Request;
import communication.Response;
import communication.ResponseType;
import domen.Automobil;
import domen.Korisnik;
import domen.PotvrdaOIznajmljivanju;
import domen.Vozac;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import oracle.jrockit.jfr.JFR;

/**
 *
 * @author aleks
 */
public class IzmenaPotvrde extends javax.swing.JDialog {

    PotvrdaOIznajmljivanju potvrdaPretrazena;

    /**
     * Creates new form IzmenaPotvrde
     */
    public IzmenaPotvrde(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbVozac = new javax.swing.JComboBox();
        txtCena = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        lblErrorID = new javax.swing.JLabel();
        lblErrorDatumOd = new javax.swing.JLabel();
        lblErrorDatumDo = new javax.swing.JLabel();
        lblErrorCena = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        cmbRegistracioniBroj = new javax.swing.JComboBox();
        datumOD = new com.toedter.calendar.JDateChooser();
        datumDO = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbVozac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCenaActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        lblErrorID.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorID.setText("jLabel7");

        lblErrorDatumOd.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorDatumOd.setText("jLabel8");

        lblErrorDatumDo.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorDatumDo.setText("jLabel9");

        lblErrorCena.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorCena.setText("jLabel10");

        jLabel1.setText("ID:");

        jLabel2.setText("Registracioni broj:");

        jLabel3.setText("Vozac:");

        jLabel4.setText("Datum od:");

        jLabel5.setText("Datum do:");

        jLabel6.setText("Cena:");

        cmbRegistracioniBroj.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErrorCena)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(datumDO, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addComponent(datumOD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(37, 37, 37))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorDatumDo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jLabel1)
                        .addComponent(lblErrorID)
                        .addComponent(lblErrorDatumOd))
                    .addGap(104, 104, 104)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbVozac, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbRegistracioniBroj, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(172, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(datumOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(datumDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorCena)
                .addGap(4, 4, 4)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblErrorID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbRegistracioniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(cmbVozac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(45, 45, 45)
                    .addComponent(lblErrorDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addGap(10, 10, 10)
                    .addComponent(lblErrorDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCenaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        if (validacija()) {
            return;
        }

        int id = Integer.parseInt(txtID.getText());
        Automobil auto = (Automobil) cmbRegistracioniBroj.getSelectedItem();
        Vozac vozac = (Vozac) cmbVozac.getSelectedItem();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datumOd = datumOD.getDate();
        Date datumDo = datumDO.getDate();
        double cena = Double.parseDouble(txtCena.getText());

        Korisnik korisnik = Communication.getInstance().getUlogovani();
        PotvrdaOIznajmljivanju potvrda = new PotvrdaOIznajmljivanju(id, datumOd, datumDo, cena, auto, vozac, korisnik);

        Request request = new Request(Operations.EDIT_CONFIRMATION, potvrda);
        Response response = Communication.getInstance().editConfirmation(request);

        if (response.getResponseType().equals(ResponseType.SUCCESS)) {
            JOptionPane.showMessageDialog(this, "Potvrda je uspesno izmenjena!");

        } else {
            JOptionPane.showMessageDialog(this, "Neuspesno izmenjena potvda", "Greska", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmenaPotvrde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmenaPotvrde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmenaPotvrde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmenaPotvrde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzmenaPotvrde dialog = new IzmenaPotvrde(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbRegistracioniBroj;
    private javax.swing.JComboBox cmbVozac;
    private com.toedter.calendar.JDateChooser datumDO;
    private com.toedter.calendar.JDateChooser datumOD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblErrorCena;
    private javax.swing.JLabel lblErrorDatumDo;
    private javax.swing.JLabel lblErrorDatumOd;
    private javax.swing.JLabel lblErrorID;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables

    void setPotvrda(PotvrdaOIznajmljivanju potvrdaPretrazena) {
        this.potvrdaPretrazena = potvrdaPretrazena;
        txtID.setEnabled(false);
        txtID.setText(String.valueOf(potvrdaPretrazena.getPotvrdaID()));
        txtCena.setText(String.valueOf(potvrdaPretrazena.getCena()));
        System.out.println(potvrdaPretrazena.getDatumOD() + "");
        datumOD.setDate(potvrdaPretrazena.getDatumOD());
        datumDO.setDate(potvrdaPretrazena.getDatumDO());
    }

    private void prepareView() {
        try {

            lblErrorID.setVisible(false);
            lblErrorCena.setVisible(false);
            lblErrorDatumDo.setVisible(false);
            lblErrorDatumOd.setVisible(false);
            popuniCmbAutomobili();
            popuniCmbVozaci();

        } catch (SQLException ex) {
            Logger.getLogger(UnosPotvrde.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void popuniCmbAutomobili() throws SQLException {
        Response response = Communication.getInstance().getCars();
        ArrayList<Automobil> automobili = (ArrayList<Automobil>) response.getResult();
        cmbRegistracioniBroj.removeAllItems();

        for (Automobil automobil : automobili) {
            cmbRegistracioniBroj.addItem(automobil);

        }
    }

    private void popuniCmbVozaci() throws SQLException {
        Response response = Communication.getInstance().getDrivers();
        List<Vozac> vozaci = (List<Vozac>) response.getResult();
        cmbVozac.removeAllItems();

        for (Vozac vozac : vozaci) {
            cmbVozac.addItem(vozac);

        }
    }

    public boolean validacija() {
        lblErrorID.setVisible(false);
        lblErrorCena.setVisible(false);
        lblErrorDatumDo.setVisible(false);
        lblErrorDatumOd.setVisible(false);
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        boolean prazno = false;
        if (txtID.getText().isEmpty()) {
            lblErrorID.setText("ID je obavezan!");
            lblErrorID.setVisible(true);
            prazno = true;
        }

        if (txtCena.getText().isEmpty()) {
            lblErrorCena.setText("Cena je obavezano polje!");
            lblErrorCena.setVisible(true);
            prazno = true;
        } else if (Double.parseDouble(txtCena.getText()) <= 0) {
            lblErrorCena.setText("Cena ne sme biti manja od 0!");
            lblErrorCena.setVisible(true);
            prazno = true;
        }

        if (datumOD.getDate().before(new Date())) {
            lblErrorDatumOd.setText("Datum mora biti tekuci!");
            lblErrorDatumOd.setVisible(true);
            prazno = true;
        }

        if (datumDO.getDate().before(new Date())) {
            lblErrorDatumDo.setText("Datum mora biti tekuci!");
            lblErrorDatumDo.setVisible(true);
            prazno = true;
        }

        if (datumDO.getDate().before(datumOD.getDate())) {
            lblErrorDatumOd.setText("Datum od ne sme biti veci od datuma do!");
            lblErrorDatumOd.setVisible(true);
            prazno = true;
        }

        return prazno;
    }

}
