/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Kontroler;
import domen.Automobil;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import tableModel.TableModelAutomobili;

/**
 *
 * @author aleks
 */
public class PretragaAutomobila extends javax.swing.JFrame {

    TableModelAutomobili tma;
    Automobil pretrazenAuto;

    /**
     * Creates new form UnosAutomobila
     */
    public PretragaAutomobila() {
        initComponents();
        prepareTable();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        lblErrorPretraga.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutomobili = new javax.swing.JTable();
        btnPretraga = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        lblErrorPretraga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pretrazi automobil po registarskom broju:");

        tblAutomobili.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAutomobili);

        btnPretraga.setText("Pretrazi");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni podatke");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi podatke");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lblErrorPretraga.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPretraga.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPretraga))
                            .addComponent(lblErrorPretraga)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnIzmeni)
                        .addGap(26, 26, 26)
                        .addComponent(btnObrisi)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorPretraga)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        lblErrorPretraga.setVisible(false);
        if (txtPretraga.getText().isEmpty()) {
            lblErrorPretraga.setVisible(true);
            lblErrorPretraga.setText("Unesi registracioni broj za pretragu");
            prepareTable();
            return;
        }
        
        
        try {
            
            String regBroj = txtPretraga.getText().toUpperCase();
            pretrazenAuto = Kontroler.getInstanca().getAutomobilByRegBroj(regBroj);
            System.out.println(pretrazenAuto);
            refreshTable(pretrazenAuto);
            JOptionPane.showMessageDialog(this, "Uspesno pronadjen automobil sa registarskom oznakom: " + pretrazenAuto.getRegistracioniBroj());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            prepareTable();
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        // otvori formu za izmenu i prosledi pronadjen auto 
        if (pretrazenAuto != null) {
            IzmenaAutomobila izm = new IzmenaAutomobila(this, rootPaneCheckingEnabled);
            izm.setPretrazenAuto(pretrazenAuto);
            izm.setVisible(true);
            //osvezi tabelu
            prepareTable();

        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        if (pretrazenAuto != null) {
            try {

                Kontroler.getInstanca().obrisiAutomobil(pretrazenAuto);
                JOptionPane.showMessageDialog(this, "Uspesno obrisan automobil sa registarskom oznakom: " + pretrazenAuto.getRegistracioniBroj());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                
            }
            prepareTable();
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaAutomobila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaAutomobila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaAutomobila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaAutomobila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PretragaAutomobila().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorPretraga;
    private javax.swing.JTable tblAutomobili;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void prepareTable() {
        try {
            ArrayList<Automobil> automobili = (ArrayList<Automobil>) Kontroler.getInstanca().getStorageAutomobili();
            tma = new TableModelAutomobili(automobili);
            tblAutomobili.setModel(tma);
        } catch (Exception ex) {
            Logger.getLogger(PretragaAutomobila.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void refreshTable(Automobil auto) {

        ArrayList<Automobil> automobili = new ArrayList<>();
        automobili.add(auto);
        tma = new TableModelAutomobili(automobili);
        tblAutomobili.setModel(tma);

    }

}
