/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Kontroler;
import domen.Vozac;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tableModel.TableModelVozaci;

/**
 *
 * @author aleks
 */
public class UnosVozaca extends javax.swing.JFrame {
    Vozac vozacPretrazen;
    /**
     * Creates new form UnosVozaca
     */
    public UnosVozaca() {
        initComponents();
         prepareView();
          setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        lblIDError = new javax.swing.JLabel();
        lblErrorIme = new javax.swing.JLabel();
        lblErrorPrezime = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorAdresa = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVozaci = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        lblErrorPretraga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID vozaca:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Email:");

        jLabel5.setText("Adresa:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        txtEmail.setText(" ");

        txtAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdresaActionPerformed(evt);
            }
        });

        lblIDError.setForeground(new java.awt.Color(255, 0, 51));
        lblIDError.setText("jLabel6");

        lblErrorIme.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorIme.setText("jLabel6");

        lblErrorPrezime.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPrezime.setText("jLabel7");

        lblErrorEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorEmail.setText("jLabel6");

        lblErrorAdresa.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorAdresa.setText("jLabel7");

        jLabel6.setText("Pretrazi vozaca:");

        tblVozaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVozaci);

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        lblErrorPretraga.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPretraga.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorAdresa)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(lblErrorPrezime)
                                    .addComponent(jLabel5))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSacuvaj)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(txtAdresa)
                                    .addComponent(txtPrezime)
                                    .addComponent(txtIme)
                                    .addComponent(txtID)))
                            .addComponent(lblErrorEmail)
                            .addComponent(lblErrorIme)
                            .addComponent(lblIDError))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretrazi))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblErrorPretraga))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIzmeni)))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIDError)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addComponent(lblErrorIme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(lblErrorPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorEmail)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(lblErrorAdresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSacuvaj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPretrazi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorPretraga)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIzmeni))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdresaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
      
        if(validacija()){
            return;
        }
        
        
      int vozacID = Integer.parseInt(txtID.getText());
      String ime = txtIme.getText();
      String prezime = txtPrezime.getText();
      String email = txtEmail.getText();
      String adresa = txtAdresa.getText();
      
      Vozac v = new Vozac(vozacID, ime, prezime, email, adresa);
        try {
            Kontroler.getInstanca().dodajVozaca(v);
            JOptionPane.showMessageDialog(this, "Uspesan unos vozaca!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesan unos vozaca!\n" + ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
        popuniTabelu();
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
       lblErrorPretraga.setVisible(false);
        if (txtPretraga.getText().isEmpty()) {
            lblErrorPretraga.setVisible(true);
            lblErrorPretraga.setText("Unesi id za pretragu");
            popuniTabelu();
            return;
        }
        try {
            int id = Integer.parseInt(txtPretraga.getText());
            vozacPretrazen = Kontroler.getInstanca().getVozacByID(id);
            prikaziVozaca(vozacPretrazen);
            JOptionPane.showMessageDialog(this, "Vozac je pronadjen!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            popuniTabelu();
        }
        
        
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if (vozacPretrazen != null) {

            IzmenaVozaca izmena = new IzmenaVozaca(this, true);
            izmena.setVozac(vozacPretrazen);
            izmena.setVisible(true);

        }
        popuniTabelu();
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosVozaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosVozaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosVozaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosVozaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosVozaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorAdresa;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorIme;
    private javax.swing.JLabel lblErrorPretraga;
    private javax.swing.JLabel lblErrorPrezime;
    private javax.swing.JLabel lblIDError;
    private javax.swing.JTable tblVozaci;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPretraga;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

public boolean validacija() {
        lblIDError.setVisible(false);
        lblErrorIme.setVisible(false);
        lblErrorPrezime.setVisible(false);
        lblErrorEmail.setVisible(false);
        lblErrorAdresa.setVisible(false);
      
        boolean prazno = false;
        if (txtID.getText().isEmpty()) {
            lblIDError.setText("ID je obavezan!");
            lblIDError.setVisible(true);
            prazno = true;
        }
        
        if (txtIme.getText().isEmpty()) {
            lblErrorIme.setText("Ime je obavezano polje!");
            lblErrorIme.setVisible(true);
            prazno = true;
        }
        if (txtPrezime.getText().isEmpty()) {
            lblErrorPrezime.setText("Prezime je obavezano polje!");
            lblErrorPrezime.setVisible(true);
            prazno = true;
        }

        if (txtEmail.getText().isEmpty()) {
            lblErrorEmail.setText("Email je obavezno polje!");
            lblErrorEmail.setVisible(true);
            prazno = true;
        } else if (!txtEmail.getText().contains("@")) {
            lblErrorEmail.setText("Email mora sadrzati @!");
            lblErrorEmail.setVisible(true);
            prazno = true;
        }
        
        if (txtAdresa.getText().isEmpty()) {
            lblErrorAdresa.setText("Adresa je obavezano polje!");
            lblErrorAdresa.setVisible(true);
            prazno = true;
        }
       

        return prazno;
    }

    private void prepareView() {
        lblIDError.setVisible(false);
        lblErrorIme.setVisible(false);
        lblErrorPrezime.setVisible(false);
        lblErrorEmail.setVisible(false);
        lblErrorAdresa.setVisible(false);
        lblErrorPretraga.setVisible(false);
        popuniTabelu();
    }

    private void popuniTabelu() {
        try {
            List<Vozac> vozaci = Kontroler.getInstanca().getVozaci();
            TableModelVozaci tmv = new TableModelVozaci((ArrayList<Vozac>) vozaci);
            tblVozaci.setModel(tmv);

        } catch (Exception ex) {
            Logger.getLogger(UnosPotvrde.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void prikaziVozaca(Vozac vozac) {
        List<Vozac> vozaci = new ArrayList<>();
        vozaci.add(vozac);
        TableModelVozaci tmv = new TableModelVozaci((ArrayList<Vozac>) vozaci);
         tblVozaci.setModel(tmv);
    }


}
