/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Kontroler;
import domen.Automobil;
import domen.PotvrdaOIznajmljivanju;
import domen.Vozac;
import from.components.TableModelPotvrde;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import repository.db.RepositoryAutomobil;

/**
 *
 * @author aleks
 */
public class FrmPotvrdaTM extends javax.swing.JDialog {

    /**
     * Creates new form FrmPotvrdaTM
     */
    public FrmPotvrdaTM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            prepareView();
        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(FrmPotvrdaTM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPotvrde = new javax.swing.JTable();
        btnDodajPotvrdu = new javax.swing.JButton();
        brnObrisiPotvrdu = new javax.swing.JButton();
        btnSacuvajPotvrdu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPotvrde.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPotvrde);

        btnDodajPotvrdu.setText("Dodaj");
        btnDodajPotvrdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPotvrduActionPerformed(evt);
            }
        });

        brnObrisiPotvrdu.setText("Obrisi");
        brnObrisiPotvrdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnObrisiPotvrduActionPerformed(evt);
            }
        });

        btnSacuvajPotvrdu.setText("Sacuvaj");
        btnSacuvajPotvrdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajPotvrduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacuvajPotvrdu)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(brnObrisiPotvrdu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDodajPotvrdu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnDodajPotvrdu)
                        .addGap(18, 18, 18)
                        .addComponent(brnObrisiPotvrdu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvajPotvrdu)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnObrisiPotvrduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnObrisiPotvrduActionPerformed
       int red = tblPotvrde.getSelectedRow();
        TableModelPotvrde tbp = (TableModelPotvrde) tblPotvrde.getModel();
        if(red != -1){
            tbp.obrisiIzTabele(red);
        }else{
            JOptionPane.showMessageDialog(this, "Nije selektovan red!");
        }
    }//GEN-LAST:event_brnObrisiPotvrduActionPerformed

    private void btnDodajPotvrduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPotvrduActionPerformed
        TableModelPotvrde tmp = (TableModelPotvrde) tblPotvrde.getModel();
        tmp.dodajUTabelu(new PotvrdaOIznajmljivanju());
    }//GEN-LAST:event_btnDodajPotvrduActionPerformed

    private void btnSacuvajPotvrduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajPotvrduActionPerformed
         TableModelPotvrde tmp = (TableModelPotvrde) tblPotvrde.getModel();
         List<PotvrdaOIznajmljivanju> potvrde = tmp.getPotvrdeIzTabele();
         for (PotvrdaOIznajmljivanju potvrda : potvrde) {
             potvrda.setKorisnik(Kontroler.getInstanca().getUlogovaniKorisnik());
            
        }
        try {
            Kontroler.getInstanca().dodajSvePotvrde(potvrde);
            JOptionPane.showMessageDialog(this, "Uspesno cuvanje!","",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex.getMessage(),"cUVANJE nije uspelo!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajPotvrduActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPotvrdaTM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPotvrdaTM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPotvrdaTM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPotvrdaTM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPotvrdaTM dialog = new FrmPotvrdaTM(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnObrisiPotvrdu;
    private javax.swing.JButton btnDodajPotvrdu;
    private javax.swing.JButton btnSacuvajPotvrdu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPotvrde;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws SQLException {
        prepareTable();
    }

    private void prepareTable() throws SQLException {
        List<PotvrdaOIznajmljivanju> potvrde = new ArrayList<>();
        TableModelPotvrde model = new TableModelPotvrde(potvrde);
        tblPotvrde.setModel(model);
       
        List<Automobil> automobili = Kontroler.getInstanca().getStorageAutomobili();
        JComboBox cbAutomobili = new JComboBox(automobili.toArray());
        TableColumn tcAutomobil = tblPotvrde.getColumnModel().getColumn(1);
        tcAutomobil.setCellEditor(new DefaultCellEditor(cbAutomobili));
        
        List<Vozac> vozaci = Kontroler.getInstanca().getStorageVozac();
        JComboBox cbVozaci = new JComboBox(vozaci.toArray());
        TableColumn tcVozaci = tblPotvrde.getColumnModel().getColumn(2);
        tcVozaci.setCellEditor(new DefaultCellEditor(cbVozaci));
    }
}
