/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author aleks
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAutomobil = new javax.swing.JMenu();
        itemDodajAutomobil = new javax.swing.JMenuItem();
        itemPretraziAutomobil = new javax.swing.JMenuItem();
        menuVozac = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuPotvrda = new javax.swing.JMenu();
        itemPotvrda = new javax.swing.JMenuItem();
        itemPretrazi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rent a car");
        setMinimumSize(new java.awt.Dimension(600, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forma/car.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        menuAutomobil.setText("Automobil");

        itemDodajAutomobil.setText("Dodaj novi");
        itemDodajAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDodajAutomobilActionPerformed(evt);
            }
        });
        menuAutomobil.add(itemDodajAutomobil);

        itemPretraziAutomobil.setText("Pretrazi automobil");
        itemPretraziAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPretraziAutomobilActionPerformed(evt);
            }
        });
        menuAutomobil.add(itemPretraziAutomobil);

        jMenuBar1.add(menuAutomobil);

        menuVozac.setText("Vozac");

        jMenuItem1.setText("Dodaj novog vozaca");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuVozac.add(jMenuItem1);

        jMenuBar1.add(menuVozac);

        menuPotvrda.setText("Potvrda");

        itemPotvrda.setText("Dodaj novu");
        itemPotvrda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPotvrdaActionPerformed(evt);
            }
        });
        menuPotvrda.add(itemPotvrda);

        itemPretrazi.setText("Pretrazi potvrdu");
        itemPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPretraziActionPerformed(evt);
            }
        });
        menuPotvrda.add(itemPretrazi);

        jMenuBar1.add(menuPotvrda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemPotvrdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPotvrdaActionPerformed
        new UnosPotvrde().setVisible(true);
    }//GEN-LAST:event_itemPotvrdaActionPerformed

    private void itemDodajAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDodajAutomobilActionPerformed
      new UnosAutomobila(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemDodajAutomobilActionPerformed

    private void itemPretraziAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPretraziAutomobilActionPerformed
       new PretragaAutomobila().setVisible(true);
    }//GEN-LAST:event_itemPretraziAutomobilActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new UnosVozaca().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPretraziActionPerformed
       new PretragaPotvrde(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_itemPretraziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemDodajAutomobil;
    private javax.swing.JMenuItem itemPotvrda;
    private javax.swing.JMenuItem itemPretrazi;
    private javax.swing.JMenuItem itemPretraziAutomobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAutomobil;
    private javax.swing.JMenu menuPotvrda;
    private javax.swing.JMenu menuVozac;
    // End of variables declaration//GEN-END:variables
}
